
name: My workflow
on:
  push:
    branches: [ main ]
    paths:
    - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'src/**'

jobs:
  main:
    uses: mohanapriya1212/spring-petclinic-GitAct/.github/workflows/maven-build.yml@main

        
      
    
    
