
name: My workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  workflow_dispatch:
    
jobs:
  main:
    uses: mohanapriya1212/spring-petclinic-GitAct/.github/workflows/maven-build.yml@main

        
      
    
    
